// frontend/src/pages/admin/mockData.js

export const mockMentorApplications = [
  // --- PENDING APPLICATIONS ---
  {
    id: '1',
    uid: 'user001',
    fullName: 'Aarav Sharma',
    jobTitle: 'Senior Software Engineer',
    company: 'Innovate Solutions',
    industry: 'Technology',
    experience: '5-10 years',
    skills: 'React, Node.js, TypeScript, AWS, System Design',
    expertise: 'Building scalable web applications and leading frontend teams.',
    achievements: 'Led the development of a new microservices architecture, reducing latency by 40%.',
    availability: '2-4 hours/week',
    mentorshipStyle: 'Hands-on, project-based guidance with a focus on best practices.',
    motivation: 'To give back to the community and help aspiring developers navigate their careers.',
    targetAudience: 'Students and early-career professionals in software development.',
    linkedinUrl: 'https://linkedin.com/in/aaravsharma',
    profilePictureUrl: '',
    status: 'pending',
  },
  {
    id: '2',
    uid: 'user002',
    fullName: 'Priya Patel',
    jobTitle: 'Product Manager',
    company: 'TechGenius',
    industry: 'Technology',
    experience: '5-10 years',
    skills: 'Product Roadmapping, Agile Methodologies, User Research, A/B Testing',
    expertise: 'SaaS product development from ideation to launch.',
    achievements: 'Launched a new feature that increased user engagement by 25%.',
    availability: '1-2 hours/week',
    mentorshipStyle: 'Strategic advice, focusing on career growth and interview preparation.',
    motivation: 'Passionate about building great products and helping others do the same.',
    targetAudience: 'Aspiring Product Managers and individuals looking to transition into product roles.',
    linkedinUrl: 'https://linkedin.com/in/priyapatel',
    profilePictureUrl: '',
    status: 'pending',
  },
  {
    id: '3',
    uid: 'user003',
    fullName: 'Rohan Mehta',
    jobTitle: 'Data Scientist',
    company: 'Data Insights Inc.',
    industry: 'Technology',
    experience: '3-5 years',
    skills: 'Python, R, Machine Learning, SQL, Tableau',
    expertise: 'Predictive modeling and data visualization.',
    achievements: 'Developed a fraud detection model that saved the company ₹50 Lakhs annually.',
    availability: 'Flexible',
    mentorshipStyle: 'I help mentees build a strong portfolio of data science projects.',
    motivation: 'I enjoy demystifying complex data concepts for newcomers.',
    targetAudience: 'Data science beginners and university students.',
    linkedinUrl: 'https://linkedin.com/in/rohanmehta',
    profilePictureUrl: '',
    status: 'pending',
  },
  {
    id: '4',
    uid: 'user004',
    fullName: 'Aditi Rao',
    jobTitle: 'Investment Banker',
    company: 'Capital Investments',
    industry: 'Finance',
    experience: '5-10 years',
    skills: 'Financial Modeling, Valuation, Mergers & Acquisitions',
    expertise: 'Corporate finance and M&A advisory.',
    achievements: 'Advised on a major cross-border acquisition valued at $200M.',
    availability: '1-2 hours/week',
    mentorshipStyle: 'Direct and practical advice on breaking into finance and acing interviews.',
    motivation: 'To guide the next generation of finance professionals in India.',
    targetAudience: 'Finance graduates and young professionals aiming for investment banking roles.',
    linkedinUrl: 'https://linkedin.com/in/aditirao',
    profilePictureUrl: '',
    status: 'pending',
  },
  {
    id: '5',
    uid: 'user005',
    fullName: 'Neha Singh',
    jobTitle: 'Digital Marketing Head',
    company: 'Growth Co.',
    industry: 'Marketing',
    experience: '10-15 years',
    skills: 'SEO, SEM, Content Strategy, Social Media Marketing',
    expertise: 'Leading digital marketing strategies for high-growth startups.',
    achievements: 'Scaled organic traffic from 10k to 500k monthly visitors in two years.',
    availability: '2-4 hours/week',
    mentorshipStyle: 'Focus on building a personal brand and strategic thinking.',
    motivation: 'Marketing is constantly evolving, and I want to share what I\'ve learned.',
    targetAudience: 'Marketing professionals and small business owners.',
    linkedinUrl: 'https://linkedin.com/in/nehasingh',
    profilePictureUrl: '',
    status: 'pending',
  },
  
  // --- APPROVED MENTORS ---
  {
    id: '6',
    uid: 'user006',
    fullName: 'Ananya Gupta',
    jobTitle: 'UX Lead',
    company: 'Creative Minds',
    industry: 'Technology',
    experience: '5-10 years',
    skills: 'User Research, Wireframing, Prototyping, Figma, Design Systems',
    expertise: 'Human-centered design for mobile and web applications.',
    achievements: 'Redesigned a mobile app checkout flow, resulting in a 15% increase in conversion.',
    availability: '1-2 hours/week',
    mentorshipStyle: 'I provide detailed portfolio reviews and case study guidance.',
    motivation: 'I believe good design can change lives and want to help others create intuitive products.',
    targetAudience: 'Aspiring UX/UI designers.',
    linkedinUrl: 'https://linkedin.com/in/ananyagupta',
    profilePictureUrl: '',
    status: 'approved',
  },
  {
    id: '7',
    uid: 'user007',
    fullName: 'Vikram Singh',
    jobTitle: 'DevOps Engineer',
    company: 'Cloud Corp',
    industry: 'Technology',
    experience: '5-10 years',
    skills: 'Kubernetes, Docker, Terraform, CI/CD, Jenkins',
    expertise: 'Cloud infrastructure and automation.',
    achievements: 'Implemented a CI/CD pipeline that reduced deployment time from 2 hours to 15 minutes.',
    availability: 'Flexible',
    mentorshipStyle: 'Practical, hands-on sessions on DevOps tools and concepts.',
    motivation: 'To help bridge the gap between development and operations.',
    targetAudience: 'Engineers interested in a career in DevOps or Site Reliability Engineering.',
    linkedinUrl: 'https://linkedin.com/in/vikramsingh',
    profilePictureUrl: '',
    status: 'approved',
  },
  {
    id: '8',
    uid: 'user008',
    fullName: 'Dr. Sameer Joshi',
    jobTitle: 'General Physician',
    company: 'City Hospital',
    industry: 'Healthcare',
    experience: '15+ years',
    skills: 'Diagnostics, Patient Management, Medical Ethics',
    expertise: 'Internal medicine and primary care.',
    achievements: 'Recognized for outstanding patient care for five consecutive years.',
    availability: '1-2 hours/week',
    mentorshipStyle: 'Guiding on the challenges and rewards of a medical career.',
    motivation: 'To inspire and guide the next generation of doctors.',
    targetAudience: 'Medical students and interns.',
    linkedinUrl: 'https://linkedin.com/in/sameerjoshi',
    profilePictureUrl: '',
    status: 'approved',
  },
  {
    id: '9',
    uid: 'user009',
    fullName: 'Kavita Iyer',
    jobTitle: 'Management Consultant',
    company: 'Strategy First',
    industry: 'Consulting',
    experience: '5-10 years',
    skills: 'Case Study Analysis, Market Sizing, Client Management',
    expertise: 'Business strategy for Fortune 500 companies.',
    achievements: 'Developed a market entry strategy for a leading e-commerce player.',
    availability: '2-4 hours/week',
    mentorshipStyle: 'Intensive case study prep and communication skills coaching.',
    motivation: 'The consulting world is challenging; I want to help others break in.',
    targetAudience: 'MBA students and aspiring consultants.',
    linkedinUrl: 'https://linkedin.com/in/kavitaiyer',
    profilePictureUrl: '',
    status: 'approved',
  },
  {
    id: '10',
    uid: 'user010',
    fullName: 'Arjun Verma',
    jobTitle: 'Lead Backend Engineer',
    company: 'ScaleUp',
    industry: 'Technology',
    experience: '10-15 years',
    skills: 'Go, Java, Microservices, System Architecture, PostgreSQL',
    expertise: 'Designing and building high-performance distributed systems.',
    achievements: 'Architected a system that handles 1 million requests per minute.',
    availability: '1-2 hours/week',
    mentorshipStyle: 'Deep dives into system design concepts and backend technologies.',
    motivation: 'I love solving complex engineering problems and sharing my knowledge.',
    targetAudience: 'Mid-level to senior backend engineers.',
    linkedinUrl: 'https://linkedin.com/in/arjunverma',
    profilePictureUrl: '',
    status: 'approved',
  },
  {
    id: '11',
    uid: 'user011',
    fullName: 'Meera Krishnan',
    jobTitle: 'Chartered Accountant',
    company: 'Krishnan & Associates',
    industry: 'Finance',
    experience: '15+ years',
    skills: 'Audit, Taxation, Financial Reporting',
    expertise: 'Corporate tax and advisory services.',
    achievements: 'Helped multiple startups navigate complex financial regulations.',
    availability: 'Flexible',
    mentorshipStyle: 'Practical advice on the CA journey and building a practice.',
    motivation: 'To support aspiring CAs through their challenging curriculum.',
    targetAudience: 'CA students and newly qualified Chartered Accountants.',
    linkedinUrl: 'https://linkedin.com/in/meerakrishnan',
    profilePictureUrl: '',
    status: 'approved',
  },
  {
    id: '12',
    uid: 'user012',
    fullName: 'Siddharth Roy',
    jobTitle: 'AI/ML Engineer',
    company: 'Future AI',
    industry: 'Technology',
    experience: '3-5 years',
    skills: 'PyTorch, TensorFlow, NLP, Computer Vision',
    expertise: 'Natural Language Processing and large language models.',
    achievements: 'Published two papers on sentiment analysis at international conferences.',
    availability: '2-4 hours/week',
    mentorshipStyle: 'Collaborative projects and research paper discussions.',
    motivation: 'AI is the future, and I am excited to help others get into this field.',
    targetAudience: 'Engineers and researchers passionate about Artificial Intelligence.',
    linkedinUrl: 'https://linkedin.com/in/siddharthroy',
    profilePictureUrl: '',
    status: 'approved',
  },
  {
    id: '13',
    uid: 'user013',
    fullName: 'Fatima Khan',
    jobTitle: 'University Professor',
    company: 'National University',
    industry: 'Education',
    experience: '15+ years',
    skills: 'Curriculum Design, Academic Research, Public Speaking',
    expertise: 'Computer Science education.',
    achievements: 'Authored a best-selling textbook on data structures.',
    availability: '1-2 hours/week',
    mentorshipStyle: 'Guidance on higher education, research, and academia.',
    motivation: 'To foster a love for learning and research in students.',
    targetAudience: 'Students considering a PhD or a career in academia.',
    linkedinUrl: 'https://linkedin.com/in/fatimakhan',
    profilePictureUrl: '',
    status: 'approved',
  },
  {
    id: '14',
    uid: 'user014',
    fullName: 'Diya Sharma',
    jobTitle: 'Content Strategist',
    company: 'Contentify',
    industry: 'Marketing',
    experience: '5-10 years',
    skills: 'Content Writing, SEO, Editorial Calendars, Brand Storytelling',
    expertise: 'Creating engaging content for B2B tech companies.',
    achievements: 'My blog post series on SaaS trends was featured in a major industry publication.',
    availability: 'Flexible',
    mentorshipStyle: 'I help mentees develop their writing voice and build a strong portfolio.',
    motivation: 'I believe in the power of words to build brands and connect with people.',
    targetAudience: 'Aspiring content writers and marketers.',
    linkedinUrl: 'https://linkedin.com/in/diyasharma',
    profilePictureUrl: '',
    status: 'approved',
  },
  {
    id: '15',
    uid: 'user015',
    fullName: 'Kabir Bedi',
    jobTitle: 'Venture Capitalist',
    company: 'NextGen Ventures',
    industry: 'Finance',
    experience: '10-15 years',
    skills: 'Deal Sourcing, Due Diligence, Startup Valuation, Pitch Deck Analysis',
    expertise: 'Early-stage investments in FinTech and HealthTech.',
    achievements: 'Led a seed round for a startup that is now a unicorn.',
    availability: '1-2 hours/week',
    mentorshipStyle: 'Direct feedback on startup ideas, pitch decks, and fundraising strategies.',
    motivation: 'To help build the next generation of great Indian startups.',
    targetAudience: 'Startup founders and aspiring venture capitalists.',
    linkedinUrl: 'https://linkedin.com/in/kabirbedi',
    profilePictureUrl: '',
    status: 'approved',
  },
  
  // --- REJECTED APPLICATIONS ---
  {
    id: '16',
    uid: 'user016',
    fullName: 'Isha Reddy',
    jobTitle: 'Frontend Developer',
    company: 'WebWeavers',
    industry: 'Technology',
    experience: '3-5 years',
    skills: 'HTML, CSS, JavaScript',
    expertise: 'Building static websites for local businesses.',
    achievements: 'Completed 10+ freelance projects.',
    availability: '4-6 hours/week',
    mentorshipStyle: 'I teach the basics of web development.',
    motivation: 'I want to share my skills.',
    targetAudience: 'Complete beginners.',
    linkedinUrl: 'https://linkedin.com/in/ishareddy',
    profilePictureUrl: '',
    status: 'rejected',
  },
  {
    id: '17',
    uid: 'user017',
    fullName: 'Vivek Nair',
    jobTitle: 'Student',
    company: 'University of Engineering',
    industry: 'Education',
    experience: '0-2 years',
    skills: 'C++, Java',
    expertise: 'Competitive programming.',
    achievements: 'Top 100 in a national coding competition.',
    availability: '4-6 hours/week',
    mentorshipStyle: 'Pair programming and problem-solving sessions.',
    motivation: 'To help other students crack coding interviews.',
    targetAudience: 'Fellow students preparing for placements.',
    linkedinUrl: 'https://linkedin.com/in/viveknair',
    profilePictureUrl: '',
    status: 'rejected',
  },
  {
    id: '18',
    uid: 'user018',
    fullName: 'Amit Kumar',
    jobTitle: 'Graphic Designer',
    company: 'Freelance',
    industry: 'Marketing',
    experience: '3-5 years',
    skills: 'Adobe Illustrator, Photoshop',
    expertise: 'Logo design and branding.',
    achievements: 'Designed logos for over 50 clients.',
    availability: 'Flexible',
    mentorshipStyle: 'Creative feedback and tool guidance.',
    motivation: 'I love design.',
    targetAudience: 'Anyone interested in graphic design.',
    linkedinUrl: 'https://linkedin.com/in/amitkumar',
    profilePictureUrl: '',
    status: 'rejected',
  },

  // --- MORE PENDING ---
  {
    id: '19',
    uid: 'user019',
    fullName: 'Sunita Menon',
    jobTitle: 'HR Business Partner',
    company: 'People First Corp',
    industry: 'Human Resources',
    experience: '10-15 years',
    skills: 'Talent Management, Employee Relations, Recruitment Strategy',
    expertise: 'Building HR processes for mid-sized tech companies.',
    achievements: 'Reduced employee attrition by 20% by implementing a new feedback system.',
    availability: '1-2 hours/week',
    mentorshipStyle: 'Guidance on navigating corporate careers and interview skills from an HR perspective.',
    motivation: 'To help candidates understand what recruiters are looking for.',
    targetAudience: 'Job seekers and HR aspirants.',
    linkedinUrl: 'https://linkedin.com/in/sunitamenon',
    profilePictureUrl: '',
    status: 'pending',
  },
  {
    id: '20',
    uid: 'user020',
    fullName: 'Rajesh Kumar',
    jobTitle: 'Civil Engineer',
    company: 'Infra Builders',
    industry: 'Engineering',
    experience: '15+ years',
    skills: 'AutoCAD, Project Management, Structural Analysis',
    expertise: 'Managing large-scale infrastructure projects like highways and bridges.',
    achievements: 'Project Manager for a key national highway expansion project.',
    availability: 'Flexible',
    mentorshipStyle: 'Sharing practical, on-the-ground knowledge of the civil engineering field.',
    motivation: 'To guide young engineers in a core engineering discipline.',
    targetAudience: 'Civil engineering students and graduates.',
    linkedinUrl: 'https://linkedin.com/in/rajeshkumar',
    profilePictureUrl: '',
    status: 'pending',
  },
];